# These are supported funding model platforms

github:           # 最多四个开启了 GitHub Sponsors 的用户名，例如：[user1，user2]
patreon:          # 一个 Patreon 用户名
open_collective:  # 一个 Open Collective 用户名
ko_fi:            # 一个 Ko-fi 用户名
tidelift:         # 一个 Tidelift 平台名称或程序包名称，例如：npm/babel
community_bridge: # 一个 Community Bridge 项目名称，例如：cloud-foundry
liberapay:        # 一个 Liberapay 用户名
issuehunt:        # 一个 IssueHunt 用户名
otechie:          # 一个 Otechie 用户名
custom:           # 最多四个自定义赞助链接，例如：['link1', 'link2']
